{
 "title": "hw4_dashboard",
 "description": "dashboard for hw4 (otus-microservice)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "app_rps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_received_total{}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "app_latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method,exported_endpoint)(rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress_latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, path, method, status)         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress_rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status, path, method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "app_500_http",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{code='500'}[1m])/rate(http_requests_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress_500_http",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(ginx_ingress_controller_request_duration_seconds_count{code='500'}[1m])/rate(nginx_ingress_controller_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}