apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:


  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: application
  type: ClusterIP
